### ISSUE TITLE
Failing to import 'EmptyDataError' from pandas.io.common

### ISSUE THREAD

**Issue by nhjjr** [inm7/cbptools#1]
Interactions with CBPtools that use `project.py` (i.e., project creation) result in an import error (`ImportError: cannot import name 'EmptyDataError'`) due to the module having been moved from `pandas.io.common` to `pandas.errors`. 

This issue has now been resolved. If encountered, please update CBPtools to the most recent version as of this writing (1.1.6). If this is not possible, the issue can alternatively be resolved by downgrading to an older version of pandas, but this is not recommended.

**Comment by kesavanpuc** [comment]
i have replaced import pandas.errors.EmptyDataError, 
now working fine
